### ISSUE TITLE
_V_ is not defined

### ISSUE THREAD

**Issue by michaelminter** [svenkroll/videojs_vast_ad_serving_plugin#1]
ReferenceError: _V_ is not defined
#2 http://0.0.0.0:3000/javascripts/vast.js:798:1
#1 http://0.0.0.0:3000/javascripts/vast.js:798:1

ReferenceError: _V_ is not defined
#2 http://0.0.0.0:3000/video5:45:3
#1 http://0.0.0.0:3000/video5:45:3 &host=0.0.0.0:3000

page: moor-vdo-pub.herokuapp.com/video5

**Comment by svenkroll** [comment]
Hi michaelminter,

you use the dev version of the videojs library. There are some differences i don't understand and one of theme ist the different naming. The minified version use "_V_" and the dev version "vjs".
